---
formatters:
  enable:
    - gci
  settings: # please keep this alphabetized
    gci:
      sections:
        - standard
        - default
        - prefix(go.etcd.io)
issues:
  exclude-files:
    - "^zz_generated.*"
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # exclude ineffassing linter for generated files for conversion
    - path: conversion\.go
      linters:
        - ineffassign
  max-same-issues: 0

linters:
  disable-all: true
  enable: # please keep this alphabetized
  # Don't use soon to deprecated[1] linters that lead to false
  # https://github.com/golangci/golangci-lint/issues/1841
  # - deadcode
  # - structcheck
  # - varcheck
    - gofmt
    - goimports
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused

linters-settings: # please keep this alphabetized
  staticcheck:
    checks:
      - "all"
      - "-SA2002"  # TODO(fix) Called testing.T.FailNow or SkipNow in a goroutine, which isn’t allowed
  stylecheck:
    checks:
      - "ST1019"  # Importing the same package multiple times.
  testifylint:
    enable-all: true
    formatter:
      require-f-funcs: true
run:
  timeout: 30m
